spring:
  config:
    activate:
      on-profile: "s3"

s3:
  credentials:
    access-key: ${S3_ACCESS_KEY:}
    secret-key: ${S3_SECRET_ACCESS_KEY:}
  bucket: ${S3_BUCKET_NAME:}
  directory: ${S3_DIRECTORY_NAME:}
  region: ap-northeast-2
