server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DATASOURCE_HOST:localhost}:3306/Record?characterEncoding=UTF-8&serverTimezone=UTC
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:}

  h2:
    console:
      enabled: true
    jpa:
      open-in-view: true
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  output:
    ansi:
      enabled: always
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  session:
    store-type: redis

logging:
  level:
    '[org.springframework.web]': INFO
    '[org.hibernate]': INFO