spring:
  config:
    activate:
      on-profile: "prod"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  config: classpath:log4j2-prod.xml
cors:
  origin: ${CORS_ORIGIN_NAME:}