server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/Record
    username: sa
    password:

  h2:
    console:
      enabled: true
    jpa:
      open-in-view: true
      hibernate:
        ddl-auto: create-drop
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
      properties:
        hibernate:
          format_sql: true
  output:
    ansi:
      enabled: always
  redis:
    host: localhost
    port: 49151
  session:
    store-type: redis

logging:
  level:
    '[org.springframework.web]': DEBUG
    '[org.hibernate]': DEBUG