server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: utf-8
spring:
  config:
    activate:
      on-profile: "dev"
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
  logging:
    level:
      '[org.springframework.web]': INFO
      '[org.hibernate]': INFO
