spring:
  config:
    activate:
      on-profile: "dev"
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  output:
    ansi:
      enabled: always
  logging:
    level:
      '[org.springframework.web]': DEBUG
      '[org.hibernate]': DEBUG
springfox:
  documentation:
    swagger:
      use-model-v3: false
logging:
  config: classpath:log4j2-dev.xml
server:
  servlet:
    session:
      cookie:
        same-site: none
        secure: true