spring:
  profiles:
    group:
      "test": "test"
      "local": "local, datasource, redis, oauth, s3"
      "dev": "dev, datasource, redis, oauth, s3"
      "prod": "prod, datasource, redis, oauth, s3"
