name: Run test on PR to develop branch

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OAUTH_KAKAO_CLIENT_ID: ${{ secrets.DEV_OAUTH_KAKAO_CLIENT_ID }}
      OAUTH_KAKAO_CLIENT_SECRET: ${{ secrets.DEV_OAUTH_KAKAO_CLIENT_SECRET }}
      OAUTH_KAKAO_REDIRECT_URL: ${{ secrets.DEV_OAUTH_KAKAO_REDIRECT_URL }}
      OAUTH_GOOGLE_CLIENT_ID: ${{ secrets.DEV_OAUTH_GOOGLE_CLIENT_ID }}
      OAUTH_GOOGLE_CLIENT_SECRET: ${{ secrets.DEV_OAUTH_GOOGLE_CLIENT_SECRET }}
      OAUTH_GOOGLE_REDIRECT_URL: ${{ secrets.DEV_OAUTH_GOOGLE_REDIRECT_URL }}
      S3_ACCESS_KEY: ${{ secrets.DEV_S3_ACCESS_KEY }}
      S3_SECRET_ACCESS_KEY: ${{ secrets.DEV_S3_SECRET_ACCESS_KEY }}
      S3_BUCKET_NAME: ${{ secrets.DEV_S3_BUCKET_NAME }}
      S3_DIRECTORY_NAME: ${{ secrets.DEV_S3_DIRECTORY_NAME }}
      CORS_ORIGIN_NAME: ${{ secrets.DEV_CORS_ORIGIN_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew clean test